services:
    ilias:
        build: .
        image: csidirop/ilias-7
        ports:
        - "127.0.0.1:80:80"
        depends_on:
            - db
        environment:
            - MARIADB_USER="${MARIADB_USER}"
            - MARIADB_PASSWORD="${MARIADB_PASSWORD}"
        volumes:
        #     - ./volumes/ilias:/var/iliasdata
            - ./volumes/log/ilias:/var/log/ilias
    db:
        image: mariadb:10
        command: --character-set-server=utf8 --collation-server=utf8_general_ci
        environment:
            - MARIADB_ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_DATABASE=ilias
            - MARIADB_USER="${MARIADB_USER}"
            - MARIADB_PASSWORD="${MARIADB_PASSWORD}"
            - MARIADB_ROOT_PASSWORD="${MARIADB_ROOT_PASSWORD}"
        # volumes:
        #     - ./volumes/mysql:/var/lib/mysql
