services:
    ilias:
        build: .
        image: csidirop/ilias-9
        ports:
        - "127.0.0.1:80:80"
        depends_on:
            - db
        environment:
            - DB_ADDR=db
            - DB_PORT=3306
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - ILIAS_ROOT_USER=${ILIAS_ROOT_USER}
            - ILIAS_ROOT_USER_PASSWORD=${ILIAS_ROOT_USER_PASSWORD}
        volumes:
        #     - ./volumes/ilias:/var/iliasdata
            - ./volumes/files:/var/www/files
            - ./volumes/log/ilias:/var/log/ilias
    db:
        image: mariadb:10
        command: --character-set-server=utf8 --collation-server=utf8_general_ci
        environment:
            - MARIADB_ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_DATABASE=ilias
            - MARIADB_USER=${DB_USER}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        # volumes:
        #     - ./volumes/mysql:/var/lib/mysql
